### ISSUE TITLE
Projeto fantástico mas...

### ISSUE THREAD

**Issue by CiceroLino** [ReversiveDev/MathfyJS#1]
Falta adicionar um estilo e clareza em seus objetivos. Se qualquer desenvolvedor meter a cara para te ajudar pode sair do jeito errado. Trabalhar com código é como trabalhar com escritores de romance que vc convida outros escritores para ajudar a escrever, cada um com seu ponto de vista sem direcionamento. 

A minha sugestão é criar uma milestone e issues com coisas que você gostaria que o pessoal pudesse fazer para te ajudar ***da sua maneira que vc gostaria q fosse***. Talvez eu esteja exagerando na sugestão, mas imaginei potencial neste seu repositório, e pensei em dar meu ponto de vista subjetivo. 

Penso também em ajudar e seria bacana vc fazer o direcionamento, exemplo... abra uma issue e escreva: **feature: add bhaskara** ou só **adicione cálculo de bhaskara**.

Seu trabalho seria só fazer merge nos pullrequests solicitados.

### Por fim

Vc vai considerar o uso do typescript tbm? Afinal, é só um outro javascript com melhorias. Eu faria essa parte como extra, afinal queria praticar uns exercícios para fortalecer ainda mais minha base .

**Comment by ReversiveDev** [comment]
Sim, eu estava pensativo quanto deixar o código em typescript, mas pelo visto é melhor que javascript para esse tipo de projeto, e agradeço sua opinião quanto as issues, vou começar a fazer isso!
